### ISSUE TITLE
Notifications were not sent to submitters (Approvers) upon creation of submission by Proxy

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/pass-notification-services#70]
2 COVID related submissions  were created by proxies. As far as we could tell, approvers who should be notified of these submissions were not notified.

**Comment by derekbelrose** [comment]
Test and Demo have been updated as of 12:54pm today

**Comment by derekbelrose** [comment]
Prod updated at 13:09

**Comment by emetsger** [comment]
This issue was due to the fact that Notification Services (NS) was using older, out-of-date libraries to interact with Fedora, e.g. the java client which used version 3.2 of the context.  The dependencies used by NS don't know how to interact with resources that use version 3.4.

When NS was reading version 3.4 resources from Fedora, it barfed, because there are new fields in the 3.4 model that the PASS java client didn't understand.

NS has been updated with an updated set of dependencies and tests against version 3.4 of the context: see https://github.com/OA-PASS/notification-services/pull/71
